# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-21 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170506_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChaseBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=True, verbose_name='\u7528\u6237ID')),
                ('coverImg', models.ImageField(default='./2706179_185025082_2.jpg', upload_to=b'', verbose_name='\u4e66\u7c4d\u5c01\u9762')),
                ('recentlyCharpterNumber', models.IntegerField(default=0, verbose_name='\u6700\u65b0\u66f4\u65b0\u7ae0\u8282\u6570')),
                ('recentlyCharpter', models.CharField(max_length=20, verbose_name='\u6700\u65b0\u7684\u7ae0\u8282')),
                ('lastReadCharpterNumber', models.IntegerField(default=0, verbose_name='\u4e0a\u6b21\u9605\u8bfb\u7684\u7ae0\u8282\u6570')),
                ('lastReadCharpter', models.CharField(max_length=20, verbose_name='\u4e0a\u6b21\u9605\u8bfb\u7684\u7ae0\u8282')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
