# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-29 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170521_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribersBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=True, verbose_name='\u7528\u6237ID')),
                ('bookName', models.CharField(max_length=20, verbose_name='\u4e66\u7c4d\u540d\u79f0')),
                ('coverImg', models.ImageField(default='./2706179_185025082_2.jpg', upload_to=b'', verbose_name='\u4e66\u7c4d\u5c01\u9762')),
                ('recentlyCharpterNumber', models.IntegerField(default=0, verbose_name='\u6700\u65b0\u66f4\u65b0\u7ae0\u8282\u6570')),
                ('recentlyCharpter', models.CharField(max_length=20, verbose_name='\u6700\u65b0\u7684\u7ae0\u8282')),
                ('lastReadCharpterNumber', models.IntegerField(default=0, verbose_name='\u4e0a\u6b21\u9605\u8bfb\u7684\u7ae0\u8282\u6570')),
                ('lastReadCharpter', models.CharField(max_length=20, verbose_name='\u4e0a\u6b21\u9605\u8bfb\u7684\u7ae0\u8282')),
            ],
        ),
        migrations.AddField(
            model_name='userchasebooks',
            name='bookName',
            field=models.CharField(default=2, max_length=20, verbose_name='\u4e66\u7c4d\u540d\u79f0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
