# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-15 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='freeBook',
            field=models.IntegerField(default=0, verbose_name='\u514d\u8d39\u7cbe\u54c1\u6392\u884c\u4f4d\u6570'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='headImgBook',
            field=models.IntegerField(default=0, verbose_name='\u9876\u90e8\u4e66\u7c4d\u63a8\u8350\u6392\u884c\u4f4d\u6570'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='hotBook',
            field=models.IntegerField(default=0, verbose_name='\u70ed\u4e66\u63a8\u8350\u6392\u884c\u4f4d\u6570'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='newBook',
            field=models.IntegerField(default=0, verbose_name='\u65b0\u4e66\u63a8\u8350\u6392\u884c\u4f4d\u6570'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='rankBook',
            field=models.IntegerField(default=0, verbose_name='\u4e0a\u67b6\u6392\u884c\u4f4d\u6570'),
        ),
    ]
