# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-22 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170515_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='testimonials',
            field=models.CharField(default=1, max_length=20, verbose_name='\u63a8\u8350\u8bed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '\u4ed9\u5251'), (2, '\u7384\u5e7b'), (3, '\u60ac\u7591'), (4, '\u5947\u5e7b'), (5, '\u519b\u4e8b'), (6, '\u5386\u53f2'), (7, '\u7ade\u6280'), (8, '\u79d1\u5e7b'), (9, '\u6821\u56ed'), (10, '\u793e\u4f1a'), (11, '\u5176\u5b83')], default=1, verbose_name='\u4e66\u7c4d\u7c7b\u578b'),
        ),
    ]
