# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-06 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentTime', models.DateTimeField(auto_created=True, verbose_name='\u6253\u8d4f\u65e5\u671f')),
                ('userId', models.IntegerField(verbose_name='\u7528\u6237id')),
                ('bookId', models.IntegerField(verbose_name='\u4e66\u7c4did')),
                ('userName', models.CharField(max_length=30, verbose_name='\u7528\u6237\u540d')),
                ('bookName', models.CharField(max_length=30, verbose_name='\u4e66\u540d')),
                ('rewardType', models.IntegerField(verbose_name='\u5956\u52b1\u7c7b\u578b')),
                ('rewardMoney', models.IntegerField(verbose_name='\u6d88\u8d39\u732b\u5e01')),
                ('productionNumber', models.IntegerField(verbose_name='\u7269\u54c1\u6570\u91cf')),
            ],
        ),
    ]
