# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-18 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayDataStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayPVNumber', models.IntegerField(default=0)),
                ('dayRechargeNumber', models.IntegerField(default=0)),
                ('dayRewardNumber', models.IntegerField(default=0)),
                ('dayLogonNumber', models.IntegerField(default=0)),
                ('dayChaseBooksNumber', models.IntegerField(default=0)),
                ('daySubscribersNumber', models.IntegerField(default=0)),
                ('produceDataDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'DayDataStatistics',
            },
        ),
        migrations.CreateModel(
            name='MonthDataStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthPVNumber', models.IntegerField(default=0)),
                ('monthRechargeNumber', models.IntegerField(default=0)),
                ('monthRewardNumber', models.IntegerField(default=0)),
                ('monthLogonNumber', models.IntegerField(default=0)),
                ('monthChaseBooksNumber', models.IntegerField(default=0)),
                ('monthSubscribersNumber', models.IntegerField(default=0)),
                ('produceDataDate', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MonthDataStatistics',
            },
        ),
    ]
