# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-06 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentTime', models.DateTimeField(auto_created=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('userId', models.IntegerField(verbose_name='\u7528\u6237id')),
                ('bookId', models.IntegerField(verbose_name='\u4e66\u7c4did')),
                ('userName', models.CharField(max_length=30, verbose_name='\u7528\u6237\u540d')),
                ('bookName', models.CharField(max_length=30, verbose_name='\u4e66\u540d')),
                ('commentType', models.IntegerField(choices=[(0, '\u4e00\u822c'), (1, '\u7cbe\u534e'), (2, '\u7f6e\u9876'), (3, '\u7cbe\u534e\u5e76\u7f6e\u9876')], verbose_name='\u8bc4\u8bba\u7c7b\u578b')),
                ('commentStick', models.BooleanField(verbose_name='\u4e66\u7c4d\u7f6e\u9876')),
                ('commentEssence', models.BooleanField(default=False, verbose_name='\u4e66\u7c4d\u7cbe\u534e')),
                ('commentTitle', models.CharField(max_length=20, verbose_name='\u8bc4\u8bba\u6807\u9898')),
                ('commentContent', models.CharField(max_length=120, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
            ],
        ),
    ]
