# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-17 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isShow',
            field=models.BooleanField(default=True, verbose_name='\u8bc4\u8bba\u662f\u5426\u663e\u793a'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentEssence',
            field=models.BooleanField(default=True, verbose_name='\u4e66\u7c4d\u7cbe\u534e'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentStick',
            field=models.BooleanField(default=True, verbose_name='\u4e66\u7c4d\u7f6e\u9876'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentType',
            field=models.IntegerField(choices=[(0, '\u4e00\u822c'), (1, '\u7cbe\u534e'), (2, '\u7f6e\u9876'), (3, '\u7cbe\u534e\u5e76\u7f6e\u9876')], default=0, verbose_name='\u8bc4\u8bba\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userId',
            field=models.IntegerField(default=0, verbose_name='\u7528\u6237id'),
        ),
    ]
